# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ReadSensorButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReadSensorButton.setGeometry(QtCore.QRect(10, 60, 101, 30))
        self.ReadSensorButton.setObjectName("ReadSensorButton")
        self.GraphHumidityButton = QtWidgets.QPushButton(self.centralwidget)
        self.GraphHumidityButton.setGeometry(QtCore.QRect(190, 110, 171, 30))
        self.GraphHumidityButton.setObjectName("GraphHumidityButton")
        self.GraphTempButton = QtWidgets.QPushButton(self.centralwidget)
        self.GraphTempButton.setGeometry(QtCore.QRect(10, 110, 171, 30))
        self.GraphTempButton.setObjectName("GraphTempButton")
        self.StatusLine = QtWidgets.QLabel(self.centralwidget)
        self.StatusLine.setGeometry(QtCore.QRect(130, 20, 301, 22))
        font = QtGui.QFont()
        font.setItalic(False)
        self.StatusLine.setFont(font)
        self.StatusLine.setMidLineWidth(0)
        self.StatusLine.setObjectName("StatusLine")
        self.CurrentSensorData = QtWidgets.QLabel(self.centralwidget)
        self.CurrentSensorData.setGeometry(QtCore.QRect(130, 70, 301, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.CurrentSensorData.setFont(font)
        self.CurrentSensorData.setObjectName("CurrentSensorData")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 40, 421, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 90, 811, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(110, 20, 20, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(110, 60, 20, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.GraphLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphLabel.setGeometry(QtCore.QRect(10, 150, 471, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.GraphLabel.setFont(font)
        self.GraphLabel.setObjectName("GraphLabel")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(420, 10, 20, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(420, 60, 20, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.TempLimitSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.TempLimitSpinBox.setGeometry(QtCore.QRect(570, 20, 50, 32))
        self.TempLimitSpinBox.setMinimum(-50)
        self.TempLimitSpinBox.setMaximum(50)
        self.TempLimitSpinBox.setProperty("value", 28)
        self.TempLimitSpinBox.setObjectName("TempLimitSpinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 0, 201, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 30, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 60, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.HumidLimitSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.HumidLimitSpinBox.setGeometry(QtCore.QRect(570, 60, 50, 32))
        self.HumidLimitSpinBox.setMinimum(0)
        self.HumidLimitSpinBox.setMaximum(100)
        self.HumidLimitSpinBox.setProperty("value", 35)
        self.HumidLimitSpinBox.setObjectName("HumidLimitSpinBox")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(620, 60, 20, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(620, 20, 20, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.TempLimitStatus = QtWidgets.QLabel(self.centralwidget)
        self.TempLimitStatus.setGeometry(QtCore.QRect(640, 30, 181, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.TempLimitStatus.setFont(font)
        self.TempLimitStatus.setMidLineWidth(0)
        self.TempLimitStatus.setObjectName("TempLimitStatus")
        self.HumidLimitStatus = QtWidgets.QLabel(self.centralwidget)
        self.HumidLimitStatus.setGeometry(QtCore.QRect(640, 70, 181, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.HumidLimitStatus.setFont(font)
        self.HumidLimitStatus.setMidLineWidth(0)
        self.HumidLimitStatus.setObjectName("HumidLimitStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ReadSensorButton.setText(_translate("MainWindow", "Read Sensor"))
        self.GraphHumidityButton.setText(_translate("MainWindow", "Graph Recent Humidity"))
        self.GraphTempButton.setText(_translate("MainWindow", "Graph Recent Temp"))
        self.StatusLine.setText(_translate("MainWindow", "Current device status"))
        self.CurrentSensorData.setText(_translate("MainWindow", "Select to display the current sensor data"))
        self.label.setText(_translate("MainWindow", "App Status"))
        self.GraphLabel.setText(_translate("MainWindow", "Selecting the buttons above will display the last 10 DB stored samples"))
        self.label_2.setText(_translate("MainWindow", "Sensor Upper Alarm Limits"))
        self.label_3.setText(_translate("MainWindow", "Temp Limit (C)"))
        self.label_4.setText(_translate("MainWindow", "Humidity Limit (%)"))
        self.TempLimitStatus.setText(_translate("MainWindow", "Awaiting Temp Sample"))
        self.HumidLimitStatus.setText(_translate("MainWindow", "Awaiting Humidity Sample"))

