# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 329)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ReadSensorButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReadSensorButton.setGeometry(QtCore.QRect(10, 60, 101, 30))
        self.ReadSensorButton.setObjectName("ReadSensorButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(10, 220, 119, 27))
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 190, 119, 27))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.GraphHumidityButton = QtWidgets.QPushButton(self.centralwidget)
        self.GraphHumidityButton.setGeometry(QtCore.QRect(10, 150, 171, 30))
        self.GraphHumidityButton.setObjectName("GraphHumidityButton")
        self.GraphTempButton = QtWidgets.QPushButton(self.centralwidget)
        self.GraphTempButton.setGeometry(QtCore.QRect(10, 110, 171, 30))
        self.GraphTempButton.setObjectName("GraphTempButton")
        self.StatusLine = QtWidgets.QLabel(self.centralwidget)
        self.StatusLine.setGeometry(QtCore.QRect(130, 20, 301, 22))
        self.StatusLine.setMidLineWidth(0)
        self.StatusLine.setObjectName("StatusLine")
        self.CurrentSensorData = QtWidgets.QLabel(self.centralwidget)
        self.CurrentSensorData.setGeometry(QtCore.QRect(130, 60, 301, 22))
        self.CurrentSensorData.setObjectName("CurrentSensorData")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 40, 421, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 90, 421, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(110, 20, 20, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(110, 60, 20, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ReadSensorButton.setText(_translate("MainWindow", "Read Sensor"))
        self.radioButton.setText(_translate("MainWindow", "Degrees F"))
        self.radioButton_2.setText(_translate("MainWindow", "Degrees C"))
        self.GraphHumidityButton.setText(_translate("MainWindow", "Graph Recent Humidity"))
        self.GraphTempButton.setText(_translate("MainWindow", "Graph Recent Temp"))
        self.StatusLine.setText(_translate("MainWindow", "StatusLine"))
        self.CurrentSensorData.setText(_translate("MainWindow", "ReturnedData"))
        self.label.setText(_translate("MainWindow", "App Status"))

